//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIDWrapper
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthenticateRequest", Namespace="http://schemas.datacontract.org/2004/07/GeneralContract.Entites")]
    public partial class AuthenticateRequest : object
    {
        
        private string AdditionalDataField;
        
        private string AuthenticationReasonArField;
        
        private string AuthenticationReasonEnField;
        
        private string ChallengeField;
        
        private string PersonCivilNoField;
        
        private string RefIdField;
        
        private bool RequestUserDetailsField;
        
        private string SPCallbackURLField;
        
        private string ServiceDescriptionARField;
        
        private string ServiceDescriptionENField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdditionalData
        {
            get
            {
                return this.AdditionalDataField;
            }
            set
            {
                this.AdditionalDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AuthenticationReasonAr
        {
            get
            {
                return this.AuthenticationReasonArField;
            }
            set
            {
                this.AuthenticationReasonArField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AuthenticationReasonEn
        {
            get
            {
                return this.AuthenticationReasonEnField;
            }
            set
            {
                this.AuthenticationReasonEnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Challenge
        {
            get
            {
                return this.ChallengeField;
            }
            set
            {
                this.ChallengeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PersonCivilNo
        {
            get
            {
                return this.PersonCivilNoField;
            }
            set
            {
                this.PersonCivilNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RefId
        {
            get
            {
                return this.RefIdField;
            }
            set
            {
                this.RefIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool RequestUserDetails
        {
            get
            {
                return this.RequestUserDetailsField;
            }
            set
            {
                this.RequestUserDetailsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SPCallbackURL
        {
            get
            {
                return this.SPCallbackURLField;
            }
            set
            {
                this.SPCallbackURLField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceDescriptionAR
        {
            get
            {
                return this.ServiceDescriptionARField;
            }
            set
            {
                this.ServiceDescriptionARField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceDescriptionEN
        {
            get
            {
                return this.ServiceDescriptionENField;
            }
            set
            {
                this.ServiceDescriptionENField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MIDAuthSignClientResponseOfAuthenticationQRDataOmWmLNjX", Namespace="http://schemas.datacontract.org/2004/07/MIDAuthSignContract.Entities")]
    public partial class MIDAuthSignClientResponseOfAuthenticationQRDataOmWmLNjX : object
    {
        
        private MIDWrapper.AuthenticationQRData DataField;
        
        private MIDWrapper.CuError ErrorField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MIDWrapper.AuthenticationQRData Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MIDWrapper.CuError Error
        {
            get
            {
                return this.ErrorField;
            }
            set
            {
                this.ErrorField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthenticationQRData", Namespace="http://schemas.datacontract.org/2004/07/MIDAuthSignContract.Entities")]
    public partial class AuthenticationQRData : object
    {
        
        private string QRCodeField;
        
        private string QRCodeImageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QRCode
        {
            get
            {
                return this.QRCodeField;
            }
            set
            {
                this.QRCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QRCodeImage
        {
            get
            {
                return this.QRCodeImageField;
            }
            set
            {
                this.QRCodeImageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CuError", Namespace="http://schemas.datacontract.org/2004/07/MIDAuthSignContract.Entities")]
    public partial class CuError : object
    {
        
        private int CodeField;
        
        private string MessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MIDAssuranceLevel", Namespace="http://schemas.datacontract.org/2004/07/GeneralContract.Enums")]
    public enum MIDAssuranceLevel : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Medium = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        High = 30,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MIDAuthSignClientResponseOfstring", Namespace="http://schemas.datacontract.org/2004/07/MIDAuthSignContract.Entities")]
    public partial class MIDAuthSignClientResponseOfstring : object
    {
        
        private string DataField;
        
        private MIDWrapper.CuError ErrorField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MIDWrapper.CuError Error
        {
            get
            {
                return this.ErrorField;
            }
            set
            {
                this.ErrorField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MIDAuthSignClientResponseOfPersonalDataOmWmLNjX", Namespace="http://schemas.datacontract.org/2004/07/MIDAuthSignContract.Entities")]
    public partial class MIDAuthSignClientResponseOfPersonalDataOmWmLNjX : object
    {
        
        private MIDWrapper.PersonalData DataField;
        
        private MIDWrapper.CuError ErrorField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MIDWrapper.PersonalData Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MIDWrapper.CuError Error
        {
            get
            {
                return this.ErrorField;
            }
            set
            {
                this.ErrorField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonalData", Namespace="http://schemas.datacontract.org/2004/07/MIDAuthSignContract.Entities")]
    public partial class PersonalData : object
    {
        
        private MIDWrapper.Address AddressField;
        
        private System.DateTime BirthDateField;
        
        private string BloodGroupField;
        
        private System.DateTime CardExpiryDateField;
        
        private string CivilIDField;
        
        private string EmailAddressField;
        
        private string FullNameArField;
        
        private string FullNameEnField;
        
        private string GenderField;
        
        private MIDWrapper.GovIdData GovDataField;
        
        private string MobileNumberField;
        
        private string NationalityArField;
        
        private string NationalityEnField;
        
        private byte[] NationalityFlagField;
        
        private string PhotoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MIDWrapper.Address Address
        {
            get
            {
                return this.AddressField;
            }
            set
            {
                this.AddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime BirthDate
        {
            get
            {
                return this.BirthDateField;
            }
            set
            {
                this.BirthDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BloodGroup
        {
            get
            {
                return this.BloodGroupField;
            }
            set
            {
                this.BloodGroupField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CardExpiryDate
        {
            get
            {
                return this.CardExpiryDateField;
            }
            set
            {
                this.CardExpiryDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CivilID
        {
            get
            {
                return this.CivilIDField;
            }
            set
            {
                this.CivilIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailAddress
        {
            get
            {
                return this.EmailAddressField;
            }
            set
            {
                this.EmailAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullNameAr
        {
            get
            {
                return this.FullNameArField;
            }
            set
            {
                this.FullNameArField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullNameEn
        {
            get
            {
                return this.FullNameEnField;
            }
            set
            {
                this.FullNameEnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gender
        {
            get
            {
                return this.GenderField;
            }
            set
            {
                this.GenderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MIDWrapper.GovIdData GovData
        {
            get
            {
                return this.GovDataField;
            }
            set
            {
                this.GovDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MobileNumber
        {
            get
            {
                return this.MobileNumberField;
            }
            set
            {
                this.MobileNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NationalityAr
        {
            get
            {
                return this.NationalityArField;
            }
            set
            {
                this.NationalityArField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NationalityEn
        {
            get
            {
                return this.NationalityEnField;
            }
            set
            {
                this.NationalityEnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] NationalityFlag
        {
            get
            {
                return this.NationalityFlagField;
            }
            set
            {
                this.NationalityFlagField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Photo
        {
            get
            {
                return this.PhotoField;
            }
            set
            {
                this.PhotoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Address", Namespace="http://schemas.datacontract.org/2004/07/MIDAuthSignContract.Entities")]
    public partial class Address : object
    {
        
        private string AreaField;
        
        private string BlockNumberField;
        
        private string BuildingNumberField;
        
        private string BuildingTypeField;
        
        private string FloorNumberField;
        
        private string PaciBuildingNumberField;
        
        private string StreetNameField;
        
        private string UnitNumberField;
        
        private string UnitTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Area
        {
            get
            {
                return this.AreaField;
            }
            set
            {
                this.AreaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BlockNumber
        {
            get
            {
                return this.BlockNumberField;
            }
            set
            {
                this.BlockNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BuildingNumber
        {
            get
            {
                return this.BuildingNumberField;
            }
            set
            {
                this.BuildingNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BuildingType
        {
            get
            {
                return this.BuildingTypeField;
            }
            set
            {
                this.BuildingTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FloorNumber
        {
            get
            {
                return this.FloorNumberField;
            }
            set
            {
                this.FloorNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaciBuildingNumber
        {
            get
            {
                return this.PaciBuildingNumberField;
            }
            set
            {
                this.PaciBuildingNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StreetName
        {
            get
            {
                return this.StreetNameField;
            }
            set
            {
                this.StreetNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnitNumber
        {
            get
            {
                return this.UnitNumberField;
            }
            set
            {
                this.UnitNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnitType
        {
            get
            {
                return this.UnitTypeField;
            }
            set
            {
                this.UnitTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GovIdData", Namespace="http://schemas.datacontract.org/2004/07/MIDAuthSignContract.Entities")]
    public partial class GovIdData : object
    {
        
        private string MOIReferenceField;
        
        private string SponsorNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MOIReference
        {
            get
            {
                return this.MOIReferenceField;
            }
            set
            {
                this.MOIReferenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SponsorName
        {
            get
            {
                return this.SponsorNameField;
            }
            set
            {
                this.SponsorNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MIDAuthSignClientResponseOfRequestStatusExBvhZr4Id", Namespace="http://schemas.datacontract.org/2004/07/MIDAuthSignContract.Entities")]
    public partial class MIDAuthSignClientResponseOfRequestStatusExBvhZr4Id : object
    {
        
        private MIDWrapper.RequestStatusEx DataField;
        
        private MIDWrapper.CuError ErrorField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MIDWrapper.RequestStatusEx Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MIDWrapper.CuError Error
        {
            get
            {
                return this.ErrorField;
            }
            set
            {
                this.ErrorField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestStatusEx", Namespace="http://schemas.datacontract.org/2004/07/GeneralContract.Entites")]
    public partial class RequestStatusEx : object
    {
        
        private string CallBackExField;
        
        private MIDWrapper.CallBackRespone CallBackResponeField;
        
        private string CivilNoField;
        
        private System.Nullable<int> HTTPStatusField;
        
        private string RefIdField;
        
        private string RequestIdField;
        
        private string RequestStatusField;
        
        private System.Nullable<int> RequestStatusIdField;
        
        private string ResultCodeField;
        
        private System.Nullable<int> ResultCodeIdField;
        
        private string UserActionField;
        
        private System.Nullable<int> UserActionIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CallBackEx
        {
            get
            {
                return this.CallBackExField;
            }
            set
            {
                this.CallBackExField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MIDWrapper.CallBackRespone CallBackRespone
        {
            get
            {
                return this.CallBackResponeField;
            }
            set
            {
                this.CallBackResponeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CivilNo
        {
            get
            {
                return this.CivilNoField;
            }
            set
            {
                this.CivilNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> HTTPStatus
        {
            get
            {
                return this.HTTPStatusField;
            }
            set
            {
                this.HTTPStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RefId
        {
            get
            {
                return this.RefIdField;
            }
            set
            {
                this.RefIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RequestId
        {
            get
            {
                return this.RequestIdField;
            }
            set
            {
                this.RequestIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RequestStatus
        {
            get
            {
                return this.RequestStatusField;
            }
            set
            {
                this.RequestStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> RequestStatusId
        {
            get
            {
                return this.RequestStatusIdField;
            }
            set
            {
                this.RequestStatusIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResultCode
        {
            get
            {
                return this.ResultCodeField;
            }
            set
            {
                this.ResultCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ResultCodeId
        {
            get
            {
                return this.ResultCodeIdField;
            }
            set
            {
                this.ResultCodeIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserAction
        {
            get
            {
                return this.UserActionField;
            }
            set
            {
                this.UserActionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> UserActionId
        {
            get
            {
                return this.UserActionIdField;
            }
            set
            {
                this.UserActionIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CallBackRespone", Namespace="http://schemas.datacontract.org/2004/07/GeneralContract.Entites")]
    public partial class CallBackRespone : object
    {
        
        private MIDWrapper.MidAuthSignResponse MIDAuthSignResponseField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MIDWrapper.MidAuthSignResponse MIDAuthSignResponse
        {
            get
            {
                return this.MIDAuthSignResponseField;
            }
            set
            {
                this.MIDAuthSignResponseField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MidAuthSignResponse", Namespace="http://schemas.datacontract.org/2004/07/GeneralContract.Entites")]
    public partial class MidAuthSignResponse : object
    {
        
        private MIDWrapper.PersonalData1 PersonalDataField;
        
        private MIDWrapper.RequestDetails RequestDetailsField;
        
        private MIDWrapper.ResultDetails ResultDetailsField;
        
        private MIDWrapper.Signature SignatureField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MIDWrapper.PersonalData1 PersonalData
        {
            get
            {
                return this.PersonalDataField;
            }
            set
            {
                this.PersonalDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MIDWrapper.RequestDetails RequestDetails
        {
            get
            {
                return this.RequestDetailsField;
            }
            set
            {
                this.RequestDetailsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MIDWrapper.ResultDetails ResultDetails
        {
            get
            {
                return this.ResultDetailsField;
            }
            set
            {
                this.ResultDetailsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MIDWrapper.Signature Signature
        {
            get
            {
                return this.SignatureField;
            }
            set
            {
                this.SignatureField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonalData", Namespace="http://schemas.datacontract.org/2004/07/GeneralContract.Entites")]
    public partial class PersonalData1 : object
    {
        
        private MIDWrapper.Address1 AddressField;
        
        private System.Nullable<System.DateTime> BirthDateField;
        
        private string BloodGroupField;
        
        private System.Nullable<System.DateTime> CardExpiryDateField;
        
        private string CivilIdField;
        
        private string DocumentNumberField;
        
        private string EmailAddressField;
        
        private string FullNameArField;
        
        private string FullNameEnField;
        
        private string GenderField;
        
        private MIDWrapper.GovData GovDataField;
        
        private string MobileNumberField;
        
        private string NationalityArField;
        
        private string NationalityEnField;
        
        private string PassportNumberField;
        
        private string PhotoField;
        
        private string ProfessionDetailsField;
        
        private string ResidencyTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MIDWrapper.Address1 Address
        {
            get
            {
                return this.AddressField;
            }
            set
            {
                this.AddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> BirthDate
        {
            get
            {
                return this.BirthDateField;
            }
            set
            {
                this.BirthDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BloodGroup
        {
            get
            {
                return this.BloodGroupField;
            }
            set
            {
                this.BloodGroupField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CardExpiryDate
        {
            get
            {
                return this.CardExpiryDateField;
            }
            set
            {
                this.CardExpiryDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CivilId
        {
            get
            {
                return this.CivilIdField;
            }
            set
            {
                this.CivilIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentNumber
        {
            get
            {
                return this.DocumentNumberField;
            }
            set
            {
                this.DocumentNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailAddress
        {
            get
            {
                return this.EmailAddressField;
            }
            set
            {
                this.EmailAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullNameAr
        {
            get
            {
                return this.FullNameArField;
            }
            set
            {
                this.FullNameArField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullNameEn
        {
            get
            {
                return this.FullNameEnField;
            }
            set
            {
                this.FullNameEnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gender
        {
            get
            {
                return this.GenderField;
            }
            set
            {
                this.GenderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MIDWrapper.GovData GovData
        {
            get
            {
                return this.GovDataField;
            }
            set
            {
                this.GovDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MobileNumber
        {
            get
            {
                return this.MobileNumberField;
            }
            set
            {
                this.MobileNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NationalityAr
        {
            get
            {
                return this.NationalityArField;
            }
            set
            {
                this.NationalityArField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NationalityEn
        {
            get
            {
                return this.NationalityEnField;
            }
            set
            {
                this.NationalityEnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PassportNumber
        {
            get
            {
                return this.PassportNumberField;
            }
            set
            {
                this.PassportNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Photo
        {
            get
            {
                return this.PhotoField;
            }
            set
            {
                this.PhotoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProfessionDetails
        {
            get
            {
                return this.ProfessionDetailsField;
            }
            set
            {
                this.ProfessionDetailsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResidencyType
        {
            get
            {
                return this.ResidencyTypeField;
            }
            set
            {
                this.ResidencyTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestDetails", Namespace="http://schemas.datacontract.org/2004/07/GeneralContract.Entites")]
    public partial class RequestDetails : object
    {
        
        private string AdditionalDataField;
        
        private string ChallengeField;
        
        private string CivilNoField;
        
        private string RequestIDField;
        
        private string RequestTypeField;
        
        private string ServiceProviderIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdditionalData
        {
            get
            {
                return this.AdditionalDataField;
            }
            set
            {
                this.AdditionalDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Challenge
        {
            get
            {
                return this.ChallengeField;
            }
            set
            {
                this.ChallengeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CivilNo
        {
            get
            {
                return this.CivilNoField;
            }
            set
            {
                this.CivilNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RequestID
        {
            get
            {
                return this.RequestIDField;
            }
            set
            {
                this.RequestIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RequestType
        {
            get
            {
                return this.RequestTypeField;
            }
            set
            {
                this.RequestTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceProviderId
        {
            get
            {
                return this.ServiceProviderIdField;
            }
            set
            {
                this.ServiceProviderIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultDetails", Namespace="http://schemas.datacontract.org/2004/07/GeneralContract.Entites")]
    public partial class ResultDetails : object
    {
        
        private string HashAlgorithmField;
        
        private string ResultCodeField;
        
        private string SignatureDataField;
        
        private string SigningDatatypeField;
        
        private System.Nullable<System.DateTime> TransactionDateField;
        
        private string UserActionField;
        
        private string UserCertificateField;
        
        private string UserCivilNoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HashAlgorithm
        {
            get
            {
                return this.HashAlgorithmField;
            }
            set
            {
                this.HashAlgorithmField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResultCode
        {
            get
            {
                return this.ResultCodeField;
            }
            set
            {
                this.ResultCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SignatureData
        {
            get
            {
                return this.SignatureDataField;
            }
            set
            {
                this.SignatureDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SigningDatatype
        {
            get
            {
                return this.SigningDatatypeField;
            }
            set
            {
                this.SigningDatatypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> TransactionDate
        {
            get
            {
                return this.TransactionDateField;
            }
            set
            {
                this.TransactionDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserAction
        {
            get
            {
                return this.UserActionField;
            }
            set
            {
                this.UserActionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserCertificate
        {
            get
            {
                return this.UserCertificateField;
            }
            set
            {
                this.UserCertificateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserCivilNo
        {
            get
            {
                return this.UserCivilNoField;
            }
            set
            {
                this.UserCivilNoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Signature", Namespace="http://schemas.datacontract.org/2004/07/GeneralContract.Entites")]
    public partial class Signature : object
    {
        
        private string SignatureDataField;
        
        private string SigningCertificateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SignatureData
        {
            get
            {
                return this.SignatureDataField;
            }
            set
            {
                this.SignatureDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SigningCertificate
        {
            get
            {
                return this.SigningCertificateField;
            }
            set
            {
                this.SigningCertificateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Address", Namespace="http://schemas.datacontract.org/2004/07/GeneralContract.Entites")]
    public partial class Address1 : object
    {
        
        private string AreaField;
        
        private string BlockNumberField;
        
        private string BuildingNumberField;
        
        private string BuildingTypeField;
        
        private string FloorNumberField;
        
        private string GovernerateField;
        
        private string PaciBuildingNumberField;
        
        private string StreetNameField;
        
        private string UnitNumberField;
        
        private string UnitTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Area
        {
            get
            {
                return this.AreaField;
            }
            set
            {
                this.AreaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BlockNumber
        {
            get
            {
                return this.BlockNumberField;
            }
            set
            {
                this.BlockNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BuildingNumber
        {
            get
            {
                return this.BuildingNumberField;
            }
            set
            {
                this.BuildingNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BuildingType
        {
            get
            {
                return this.BuildingTypeField;
            }
            set
            {
                this.BuildingTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FloorNumber
        {
            get
            {
                return this.FloorNumberField;
            }
            set
            {
                this.FloorNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Governerate
        {
            get
            {
                return this.GovernerateField;
            }
            set
            {
                this.GovernerateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaciBuildingNumber
        {
            get
            {
                return this.PaciBuildingNumberField;
            }
            set
            {
                this.PaciBuildingNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StreetName
        {
            get
            {
                return this.StreetNameField;
            }
            set
            {
                this.StreetNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnitNumber
        {
            get
            {
                return this.UnitNumberField;
            }
            set
            {
                this.UnitNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnitType
        {
            get
            {
                return this.UnitTypeField;
            }
            set
            {
                this.UnitTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GovData", Namespace="http://schemas.datacontract.org/2004/07/GeneralContract.Entites")]
    public partial class GovData : object
    {
        
        private System.Nullable<System.DateTime> CivilIdExpiryDateField;
        
        private string MoiReferenceField;
        
        private string SponsorNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CivilIdExpiryDate
        {
            get
            {
                return this.CivilIdExpiryDateField;
            }
            set
            {
                this.CivilIdExpiryDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MoiReference
        {
            get
            {
                return this.MoiReferenceField;
            }
            set
            {
                this.MoiReferenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SponsorName
        {
            get
            {
                return this.SponsorNameField;
            }
            set
            {
                this.SponsorNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MIDAuthSignClientResponseOfHasMobileIdResponseOmWmLNjX", Namespace="http://schemas.datacontract.org/2004/07/MIDAuthSignContract.Entities")]
    public partial class MIDAuthSignClientResponseOfHasMobileIdResponseOmWmLNjX : object
    {
        
        private MIDWrapper.HasMobileIdResponse DataField;
        
        private MIDWrapper.CuError ErrorField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MIDWrapper.HasMobileIdResponse Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MIDWrapper.CuError Error
        {
            get
            {
                return this.ErrorField;
            }
            set
            {
                this.ErrorField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HasMobileIdResponse", Namespace="http://schemas.datacontract.org/2004/07/MIDAuthSignContract.Entities")]
    public partial class HasMobileIdResponse : object
    {
        
        private string CivilNoField;
        
        private bool HasMobileIdField;
        
        private string StatusField;
        
        private string VerificationLevelField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CivilNo
        {
            get
            {
                return this.CivilNoField;
            }
            set
            {
                this.CivilNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasMobileId
        {
            get
            {
                return this.HasMobileIdField;
            }
            set
            {
                this.HasMobileIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VerificationLevel
        {
            get
            {
                return this.VerificationLevelField;
            }
            set
            {
                this.VerificationLevelField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MIDNotificationRequest", Namespace="http://schemas.datacontract.org/2004/07/GeneralContract.Entites")]
    public partial class MIDNotificationRequest : object
    {
        
        private string NotificationMessageArField;
        
        private string NotificationMessageEnField;
        
        private string NotificationSubjectArField;
        
        private string NotificationSubjectEnField;
        
        private string PersonCivilNoField;
        
        private string RefIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NotificationMessageAr
        {
            get
            {
                return this.NotificationMessageArField;
            }
            set
            {
                this.NotificationMessageArField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NotificationMessageEn
        {
            get
            {
                return this.NotificationMessageEnField;
            }
            set
            {
                this.NotificationMessageEnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NotificationSubjectAr
        {
            get
            {
                return this.NotificationSubjectArField;
            }
            set
            {
                this.NotificationSubjectArField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NotificationSubjectEn
        {
            get
            {
                return this.NotificationSubjectEnField;
            }
            set
            {
                this.NotificationSubjectEnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PersonCivilNo
        {
            get
            {
                return this.PersonCivilNoField;
            }
            set
            {
                this.PersonCivilNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RefId
        {
            get
            {
                return this.RefIdField;
            }
            set
            {
                this.RefIdField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MIDWrapper.IMIDWrapper")]
    public interface IMIDWrapper
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMIDWrapper/InitiateAuthRequestQR", ReplyAction="http://tempuri.org/IMIDWrapper/InitiateAuthRequestQRResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MIDWrapper.CuError), Action="http://tempuri.org/IMIDWrapper/InitiateAuthRequestQRCuErrorFault", Name="CuError", Namespace="http://schemas.datacontract.org/2004/07/MIDAuthSignContract.Entities")]
        MIDWrapper.MIDAuthSignClientResponseOfAuthenticationQRDataOmWmLNjX InitiateAuthRequestQR(MIDWrapper.AuthenticateRequest authRequestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMIDWrapper/InitiateAuthRequestQR", ReplyAction="http://tempuri.org/IMIDWrapper/InitiateAuthRequestQRResponse")]
        System.Threading.Tasks.Task<MIDWrapper.MIDAuthSignClientResponseOfAuthenticationQRDataOmWmLNjX> InitiateAuthRequestQRAsync(MIDWrapper.AuthenticateRequest authRequestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMIDWrapper/InitiateAuthRequestQRWithAssuranceLevel", ReplyAction="http://tempuri.org/IMIDWrapper/InitiateAuthRequestQRWithAssuranceLevelResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MIDWrapper.CuError), Action="http://tempuri.org/IMIDWrapper/InitiateAuthRequestQRWithAssuranceLevelCuErrorFaul" +
            "t", Name="CuError", Namespace="http://schemas.datacontract.org/2004/07/MIDAuthSignContract.Entities")]
        MIDWrapper.MIDAuthSignClientResponseOfAuthenticationQRDataOmWmLNjX InitiateAuthRequestQRWithAssuranceLevel(MIDWrapper.AuthenticateRequest authRequestData, MIDWrapper.MIDAssuranceLevel assuranceLevel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMIDWrapper/InitiateAuthRequestQRWithAssuranceLevel", ReplyAction="http://tempuri.org/IMIDWrapper/InitiateAuthRequestQRWithAssuranceLevelResponse")]
        System.Threading.Tasks.Task<MIDWrapper.MIDAuthSignClientResponseOfAuthenticationQRDataOmWmLNjX> InitiateAuthRequestQRWithAssuranceLevelAsync(MIDWrapper.AuthenticateRequest authRequestData, MIDWrapper.MIDAssuranceLevel assuranceLevel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMIDWrapper/InitiateAuthRequestPN", ReplyAction="http://tempuri.org/IMIDWrapper/InitiateAuthRequestPNResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MIDWrapper.CuError), Action="http://tempuri.org/IMIDWrapper/InitiateAuthRequestPNCuErrorFault", Name="CuError", Namespace="http://schemas.datacontract.org/2004/07/MIDAuthSignContract.Entities")]
        MIDWrapper.MIDAuthSignClientResponseOfstring InitiateAuthRequestPN(MIDWrapper.AuthenticateRequest authRequestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMIDWrapper/InitiateAuthRequestPN", ReplyAction="http://tempuri.org/IMIDWrapper/InitiateAuthRequestPNResponse")]
        System.Threading.Tasks.Task<MIDWrapper.MIDAuthSignClientResponseOfstring> InitiateAuthRequestPNAsync(MIDWrapper.AuthenticateRequest authRequestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMIDWrapper/InitiateAuthRequestPNWithAssuranceLevel", ReplyAction="http://tempuri.org/IMIDWrapper/InitiateAuthRequestPNWithAssuranceLevelResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MIDWrapper.CuError), Action="http://tempuri.org/IMIDWrapper/InitiateAuthRequestPNWithAssuranceLevelCuErrorFaul" +
            "t", Name="CuError", Namespace="http://schemas.datacontract.org/2004/07/MIDAuthSignContract.Entities")]
        MIDWrapper.MIDAuthSignClientResponseOfstring InitiateAuthRequestPNWithAssuranceLevel(MIDWrapper.AuthenticateRequest authRequestData, MIDWrapper.MIDAssuranceLevel assuranceLevel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMIDWrapper/InitiateAuthRequestPNWithAssuranceLevel", ReplyAction="http://tempuri.org/IMIDWrapper/InitiateAuthRequestPNWithAssuranceLevelResponse")]
        System.Threading.Tasks.Task<MIDWrapper.MIDAuthSignClientResponseOfstring> InitiateAuthRequestPNWithAssuranceLevelAsync(MIDWrapper.AuthenticateRequest authRequestData, MIDWrapper.MIDAssuranceLevel assuranceLevel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMIDWrapper/VerifyMobileIdentityQR", ReplyAction="http://tempuri.org/IMIDWrapper/VerifyMobileIdentityQRResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MIDWrapper.CuError), Action="http://tempuri.org/IMIDWrapper/VerifyMobileIdentityQRCuErrorFault", Name="CuError", Namespace="http://schemas.datacontract.org/2004/07/MIDAuthSignContract.Entities")]
        MIDWrapper.MIDAuthSignClientResponseOfPersonalDataOmWmLNjX VerifyMobileIdentityQR(string qrCode, string refId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMIDWrapper/VerifyMobileIdentityQR", ReplyAction="http://tempuri.org/IMIDWrapper/VerifyMobileIdentityQRResponse")]
        System.Threading.Tasks.Task<MIDWrapper.MIDAuthSignClientResponseOfPersonalDataOmWmLNjX> VerifyMobileIdentityQRAsync(string qrCode, string refId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMIDWrapper/GetRequestStatus", ReplyAction="http://tempuri.org/IMIDWrapper/GetRequestStatusResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MIDWrapper.CuError), Action="http://tempuri.org/IMIDWrapper/GetRequestStatusCuErrorFault", Name="CuError", Namespace="http://schemas.datacontract.org/2004/07/MIDAuthSignContract.Entities")]
        MIDWrapper.MIDAuthSignClientResponseOfRequestStatusExBvhZr4Id GetRequestStatus(string requestId, string refId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMIDWrapper/GetRequestStatus", ReplyAction="http://tempuri.org/IMIDWrapper/GetRequestStatusResponse")]
        System.Threading.Tasks.Task<MIDWrapper.MIDAuthSignClientResponseOfRequestStatusExBvhZr4Id> GetRequestStatusAsync(string requestId, string refId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMIDWrapper/HasMobileIdentity", ReplyAction="http://tempuri.org/IMIDWrapper/HasMobileIdentityResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MIDWrapper.CuError), Action="http://tempuri.org/IMIDWrapper/HasMobileIdentityCuErrorFault", Name="CuError", Namespace="http://schemas.datacontract.org/2004/07/MIDAuthSignContract.Entities")]
        MIDWrapper.MIDAuthSignClientResponseOfHasMobileIdResponseOmWmLNjX HasMobileIdentity(string civilNo, string refId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMIDWrapper/HasMobileIdentity", ReplyAction="http://tempuri.org/IMIDWrapper/HasMobileIdentityResponse")]
        System.Threading.Tasks.Task<MIDWrapper.MIDAuthSignClientResponseOfHasMobileIdResponseOmWmLNjX> HasMobileIdentityAsync(string civilNo, string refId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMIDWrapper/NotifyPerson", ReplyAction="http://tempuri.org/IMIDWrapper/NotifyPersonResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MIDWrapper.CuError), Action="http://tempuri.org/IMIDWrapper/NotifyPersonCuErrorFault", Name="CuError", Namespace="http://schemas.datacontract.org/2004/07/MIDAuthSignContract.Entities")]
        MIDWrapper.MIDAuthSignClientResponseOfstring NotifyPerson(MIDWrapper.MIDNotificationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMIDWrapper/NotifyPerson", ReplyAction="http://tempuri.org/IMIDWrapper/NotifyPersonResponse")]
        System.Threading.Tasks.Task<MIDWrapper.MIDAuthSignClientResponseOfstring> NotifyPersonAsync(MIDWrapper.MIDNotificationRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface IMIDWrapperChannel : MIDWrapper.IMIDWrapper, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class MIDWrapperClient : System.ServiceModel.ClientBase<MIDWrapper.IMIDWrapper>, MIDWrapper.IMIDWrapper
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public MIDWrapperClient() : 
                base(MIDWrapperClient.GetDefaultBinding(), MIDWrapperClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpsBinding_IMIDWrapper.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MIDWrapperClient(EndpointConfiguration endpointConfiguration) : 
                base(MIDWrapperClient.GetBindingForEndpoint(endpointConfiguration), MIDWrapperClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MIDWrapperClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(MIDWrapperClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MIDWrapperClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(MIDWrapperClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MIDWrapperClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public MIDWrapper.MIDAuthSignClientResponseOfAuthenticationQRDataOmWmLNjX InitiateAuthRequestQR(MIDWrapper.AuthenticateRequest authRequestData)
        {
            return base.Channel.InitiateAuthRequestQR(authRequestData);
        }
        
        public System.Threading.Tasks.Task<MIDWrapper.MIDAuthSignClientResponseOfAuthenticationQRDataOmWmLNjX> InitiateAuthRequestQRAsync(MIDWrapper.AuthenticateRequest authRequestData)
        {
            return base.Channel.InitiateAuthRequestQRAsync(authRequestData);
        }
        
        public MIDWrapper.MIDAuthSignClientResponseOfAuthenticationQRDataOmWmLNjX InitiateAuthRequestQRWithAssuranceLevel(MIDWrapper.AuthenticateRequest authRequestData, MIDWrapper.MIDAssuranceLevel assuranceLevel)
        {
            return base.Channel.InitiateAuthRequestQRWithAssuranceLevel(authRequestData, assuranceLevel);
        }
        
        public System.Threading.Tasks.Task<MIDWrapper.MIDAuthSignClientResponseOfAuthenticationQRDataOmWmLNjX> InitiateAuthRequestQRWithAssuranceLevelAsync(MIDWrapper.AuthenticateRequest authRequestData, MIDWrapper.MIDAssuranceLevel assuranceLevel)
        {
            return base.Channel.InitiateAuthRequestQRWithAssuranceLevelAsync(authRequestData, assuranceLevel);
        }
        
        public MIDWrapper.MIDAuthSignClientResponseOfstring InitiateAuthRequestPN(MIDWrapper.AuthenticateRequest authRequestData)
        {
            return base.Channel.InitiateAuthRequestPN(authRequestData);
        }
        
        public System.Threading.Tasks.Task<MIDWrapper.MIDAuthSignClientResponseOfstring> InitiateAuthRequestPNAsync(MIDWrapper.AuthenticateRequest authRequestData)
        {
            return base.Channel.InitiateAuthRequestPNAsync(authRequestData);
        }
        
        public MIDWrapper.MIDAuthSignClientResponseOfstring InitiateAuthRequestPNWithAssuranceLevel(MIDWrapper.AuthenticateRequest authRequestData, MIDWrapper.MIDAssuranceLevel assuranceLevel)
        {
            return base.Channel.InitiateAuthRequestPNWithAssuranceLevel(authRequestData, assuranceLevel);
        }
        
        public System.Threading.Tasks.Task<MIDWrapper.MIDAuthSignClientResponseOfstring> InitiateAuthRequestPNWithAssuranceLevelAsync(MIDWrapper.AuthenticateRequest authRequestData, MIDWrapper.MIDAssuranceLevel assuranceLevel)
        {
            return base.Channel.InitiateAuthRequestPNWithAssuranceLevelAsync(authRequestData, assuranceLevel);
        }
        
        public MIDWrapper.MIDAuthSignClientResponseOfPersonalDataOmWmLNjX VerifyMobileIdentityQR(string qrCode, string refId)
        {
            return base.Channel.VerifyMobileIdentityQR(qrCode, refId);
        }
        
        public System.Threading.Tasks.Task<MIDWrapper.MIDAuthSignClientResponseOfPersonalDataOmWmLNjX> VerifyMobileIdentityQRAsync(string qrCode, string refId)
        {
            return base.Channel.VerifyMobileIdentityQRAsync(qrCode, refId);
        }
        
        public MIDWrapper.MIDAuthSignClientResponseOfRequestStatusExBvhZr4Id GetRequestStatus(string requestId, string refId)
        {
            return base.Channel.GetRequestStatus(requestId, refId);
        }
        
        public System.Threading.Tasks.Task<MIDWrapper.MIDAuthSignClientResponseOfRequestStatusExBvhZr4Id> GetRequestStatusAsync(string requestId, string refId)
        {
            return base.Channel.GetRequestStatusAsync(requestId, refId);
        }
        
        public MIDWrapper.MIDAuthSignClientResponseOfHasMobileIdResponseOmWmLNjX HasMobileIdentity(string civilNo, string refId)
        {
            return base.Channel.HasMobileIdentity(civilNo, refId);
        }
        
        public System.Threading.Tasks.Task<MIDWrapper.MIDAuthSignClientResponseOfHasMobileIdResponseOmWmLNjX> HasMobileIdentityAsync(string civilNo, string refId)
        {
            return base.Channel.HasMobileIdentityAsync(civilNo, refId);
        }
        
        public MIDWrapper.MIDAuthSignClientResponseOfstring NotifyPerson(MIDWrapper.MIDNotificationRequest request)
        {
            return base.Channel.NotifyPerson(request);
        }
        
        public System.Threading.Tasks.Task<MIDWrapper.MIDAuthSignClientResponseOfstring> NotifyPersonAsync(MIDWrapper.MIDNotificationRequest request)
        {
            return base.Channel.NotifyPersonAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpsBinding_IMIDWrapper))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.MessageEncoding = System.ServiceModel.WSMessageEncoding.Mtom;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpsBinding_IMIDWrapper))
            {
                return new System.ServiceModel.EndpointAddress("https://dsp-webapp01.venus.com:8151/MIDAuth/MIDSDKWrapper.MIDWrapper.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return MIDWrapperClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpsBinding_IMIDWrapper);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return MIDWrapperClient.GetEndpointAddress(EndpointConfiguration.BasicHttpsBinding_IMIDWrapper);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpsBinding_IMIDWrapper,
        }
    }
}
